### ISSUE TITLE
Release changelog is missing

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/ci-mgmt#1013]
It looks like we stopped producing useful changelogs for releases a couple of weeks ago. Examples:

- https://github.com/pulumi/pulumi-aws/releases/tag/v6.42.0 is missing https://github.com/pulumi/pulumi-aws/pull/4083
- https://github.com/pulumi/pulumi-gcp/releases is missing https://github.com/pulumi/pulumi-gcp/pull/2095

Most releases' changelog is just one last change (last commit). Instead, they should include all changes.

**Comment by corymhall** [comment]
I manually updated all of the AWS releases that were missing full release notes.

**Comment by mjeffryes** [comment]
This is probably caused by using shallow clones of the git repo so goreleaser can't find the previous tag.
