### ISSUE TITLE
AttributeError: module 'pulumi.runtime' has no attribute 'invoke_output'

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#1091]
Remediate "AttributeError: module 'pulumi.runtime' has no attribute 'invoke_output'".

From @justinvp:

These are the relevant changes and releases:
https://github.com/pulumi/pulumi/pull/17237 - Core SDK and sdkgen change for Node.js (released in v3.133.0)
https://github.com/pulumi/pulumi/pull/17275 - Core SDK and sdkgen change for Python (released in v3.134.0)
https://github.com/pulumi/pulumi/pull/17316 - Bump Node.js sdkgen’s min version to v3.133.0 (released in v3.134.0)
https://github.com/pulumi/pulumi/pull/17353 - Fix bug in Node.js Core SDK (short-circuit output invokes if inputs contains unknowns) (released in v3.134.1)
https://github.com/pulumi/pulumi/pull/17390 - Bump Node.js and Python sdkgen’s min version to v3.134.1 (released in v3.135.0)

Summary:
v3.133.0 sdkgen is problematic for Node.js. It needs v3.135.0 sdkgen and to not be setting the explicit @pulumi/pulumi dependency so that sdkgen emits the default min version.
v3.134.0 sdkgen is problematic for Python. It needs v3.135.0 sdkgen and to not be setting the explicit pulumi dependency so that sdkgen emits the default min version.

To remediate we need to make sure to remove explicit p/p dependency, for example:

- https://github.com/pulumi/pulumi-random/blob/67ad6fefe519943a878a44181fd6d957ceb5d726/provider/resources.go#L82
and
- https://github.com/pulumi/pulumi-random/blob/67ad6fefe519943a878a44181fd6d957ceb5d726/provider/resources.go#L93

Also please remove it for .NET

## Native Providers

- [x] [aws-apigateway](https://github.com/pulumi/pulumi-aws-apigateway) (not managed)
    - https://github.com/pulumi/pulumi-aws-apigateway/pull/166
- [x] [aws-native](https://github.com/pulumi/pulumi-aws-native)
- [x] [awsx](https://github.com/pulumi/pulumi-awsx) (not managed)
    - https://github.com/pulumi/pulumi-awsx/pull/1390
- [x] [azure-native](https://github.com/pulumi/pulumi-azure-native) (not managed)
  - https://github.com/pulumi/pulumi-azure-native/pull/3611 removes the bug and the urgency
  - [ ] follow up to still remove the refs for the future
- [x] [command](https://github.com/pulumi/pulumi-command)
- [x] [docker-build](https://github.com/pulumi/pulumi-docker-build)
- [x] [eks](https://github.com/pulumi/pulumi-eks) (not managed)
    - https://github.com/pulumi/pulumi-eks/pull/1414
- [ ] [google-native](https://github.com/pulumi/pulumi-google-native) (deprecated)
- [x] [kubernetes](https://github.com/pulumi/pulumi-kubernetes)
- [x] [kubernetes-cert-manager](https://github.com/pulumi/pulumi-kubernetes-cert-manager)

### Tier 1

- [x] [aws](https://github.com/pulumi/pulumi-aws) somehow clean already
- [x] [gcp](https://github.com/pulumi/pulumi-gcp)
- [x] [azure](https://github.com/pulumi/pulumi-azure)
- [x] [azuread](https://github.com/pulumi/pulumi-azuread)

### Tier 2

- [ ] [aiven](https://github.com/pulumi/pulumi-aiven)
- [ ] [akamai](https://github.com/pulumi/pulumi-akamai)
- [ ] [alicloud](https://github.com/pulumi/pulumi-alicloud)
- [ ] [archive](https://github.com/pulumi/pulumi-archive)
- [ ] [artifactory](https://github.com/pulumi/pulumi-artifactory)
- [ ] [auth0](https://github.com/pulumi/pulumi-auth0)
- [ ] [azuredevops](https://github.com/pulumi/pulumi-azuredevops)
- [ ] [civo](https://github.com/pulumi/pulumi-civo)
- [ ] [cloudamqp](https://github.com/pulumi/pulumi-cloudamqp)
- [ ] [cloudflare](https://github.com/pulumi/pulumi-cloudflare)
- [ ] [cloudinit](https://github.com/pulumi/pulumi-cloudinit)
- [ ] [confluentcloud](https://github.com/pulumi/pulumi-confluentcloud)
- [ ] [consul](https://github.com/pulumi/pulumi-consul)
- [ ] [databricks](https://github.com/pulumi/pulumi-databricks)
- [ ] [datadog](https://github.com/pulumi/pulumi-datadog)
- [ ] [digitalocean](https://github.com/pulumi/pulumi-digitalocean)
- [ ] [dnsimple](https://github.com/pulumi/pulumi-dnsimple)
- [ ] [docker](https://github.com/pulumi/pulumi-docker)
- [ ] [ec](https://github.com/pulumi/pulumi-ec)
- [ ] [external](https://github.com/pulumi/pulumi-external)
- [ ] [f5bigip](https://github.com/pulumi/pulumi-f5bigip)
- [ ] [fastly](https://github.com/pulumi/pulumi-fastly)
- [ ] [github](https://github.com/pulumi/pulumi-github)
- [ ] [gitlab](https://github.com/pulumi/pulumi-gitlab)
- [ ] [hcloud](https://github.com/pulumi/pulumi-hcloud)
- [ ] [http](https://github.com/pulumi/pulumi-http)
- [ ] [ise](https://github.com/pulumi/pulumi-ise)
- [ ] [kafka](https://github.com/pulumi/pulumi-kafka)
- [ ] [keycloak](https://github.com/pulumi/pulumi-keycloak)
- [ ] [kong](https://github.com/pulumi/pulumi-kong)
- [ ] [libvirt](https://github.com/pulumi/pulumi-libvirt)
- [ ] [linode](https://github.com/pulumi/pulumi-linode)
- [ ] [local](https://github.com/pulumi/pulumi-local)
- [ ] [mailgun](https://github.com/pulumi/pulumi-mailgun)
- [ ] [meraki](https://github.com/pulumi/pulumi-meraki)
- [ ] [minio](https://github.com/pulumi/pulumi-minio)
- [ ] [mongodbatlas](https://github.com/pulumi/pulumi-mongodbatlas)
- [ ] [mysql](https://github.com/pulumi/pulumi-mysql)
- [ ] [newrelic](https://github.com/pulumi/pulumi-newrelic)
- [ ] [nomad](https://github.com/pulumi/pulumi-nomad)
- [ ] [ns1](https://github.com/pulumi/pulumi-ns1)
- [ ] [null](https://github.com/pulumi/pulumi-null)
- [ ] [oci](https://github.com/pulumi/pulumi-oci)
- [ ] [okta](https://github.com/pulumi/pulumi-okta)
- [ ] [onelogin](https://github.com/pulumi/pulumi-onelogin)
- [ ] [openstack](https://github.com/pulumi/pulumi-openstack)
- [ ] [opsgenie](https://github.com/pulumi/pulumi-opsgenie)
- [ ] [pagerduty](https://github.com/pulumi/pulumi-pagerduty)
- [ ] [postgresql](https://github.com/pulumi/pulumi-postgresql)
- [ ] [rabbitmq](https://github.com/pulumi/pulumi-rabbitmq)
- [ ] [rancher2](https://github.com/pulumi/pulumi-rancher2)
- [ ] [random](https://github.com/pulumi/pulumi-random)
- [ ] [rke](https://github.com/pulumi/pulumi-rke)
- [ ] [signalfx](https://github.com/pulumi/pulumi-signalfx)
- [ ] [slack](https://github.com/pulumi/pulumi-slack)
- [ ] [snowflake](https://github.com/pulumi/pulumi-snowflake)
- [ ] [splunk](https://github.com/pulumi/pulumi-splunk)
- [ ] [spotinst](https://github.com/pulumi/pulumi-spotinst)
- [ ] [sumologic](https://github.com/pulumi/pulumi-sumologic)
- [ ] [tailscale](https://github.com/pulumi/pulumi-tailscale)
- [ ] [tls](https://github.com/pulumi/pulumi-tls)
- [ ] [vault](https://github.com/pulumi/pulumi-vault)
- [ ] [venafi](https://github.com/pulumi/pulumi-venafi)
- [ ] [vsphere](https://github.com/pulumi/pulumi-vsphere)
- [ ] [wavefront](https://github.com/pulumi/pulumi-wavefront)

**Comment by t0yv0** [comment]
@pulumi/providers 

I'll have a quick look at AWS ones, and tier 1.

**Comment by t0yv0** [comment]
Per @danielrbradley there are some uncertainties whether the .NET change is wanted or not so we're scoping that out and leaving as-is for now.

**Comment by t0yv0** [comment]
I'm at EOD status so far:

- aws classic seems clean already
- azuread releasing
- aws-native, azure, gcp will auto-release when approved
- k8s stood up but I'll need k8s squad to approve
- need azure squad to help with azure-native follow up but the urgent handling is done afaik

Will work with @flostadler to cover AWS Tier-x things tomorrow.

For the long tail of bridged providers I think we can script this as they're pretty uniform.

Will need to load-balance and assign remaining native ones @mjeffryes

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/ci-mgmt/pull/1092 should address this for all the lower tier providers

**Comment by flostadler** [comment]
I created PRs for AWS Tier-2+ providers and added them to the list above. For EKS I've targeted it for EKS v3 because the current v2 is not affected (uses v3.129.0 for generating the schema).

**Comment by t0yv0** [comment]
Thanks all, very fast work here!

Stood up 3 more PRs for native providers, PTAL.

google-native won't fix I think. 

Need review on those 3 PRs and still need help on azure-native, once that's in we can close I think.
