### ISSUE TITLE
Move the xyz provider upstream into the pulumi org

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/ci-mgmt#1116]
Allow the team to make changes as needed to improve the testing setup for ci-mgmt.

This currently lives in [github.com/iwahbe/terraform-provider-xyz](https://github.com/iwahbe/terraform-provider-xyz) and is owned by @iwahbe 

Current issues:
- Testing the upgrade provider workflows is impossible because it requires cutting new releases of the upstream provider.

**Comment by iwahbe** [comment]
Transfered: https://github.com/pulumi/terraform-provider-xyz.

**Comment by iwahbe** [comment]
Follow up PRs:
- https://github.com/pulumi/pulumi-xyz/pull/491
- https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/133
