### ISSUE TITLE
Upgrade workflows create duplicate issues and pull requests

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#1125]
https://github.com/pulumi/ci-mgmt/pull/1110 seems to have caused an identical issue to be created every time the upgrade workflow runs. When all of the automation succeeds without intervention, this is not a problem. But in cases where the upgrade needs manual assistance, we'll see the same issue created over and over:

![Image](https://github.com/user-attachments/assets/7c1a0107-7580-4a26-b6b0-a333657abe9e)

If an issue already exists, we should not create another one.

Additionally, if an automated pull request is not merged same-day, an (identical, most likely) new one is opened:

![Image](https://github.com/user-attachments/assets/27aa10a3-e938-47b4-9443-400dc8324e35)

**Comment by guineveresaenger** [comment]
More information:

- https://github.com/pulumi/pulumi-artifactory/issues/929 was not discovered or closed by https://github.com/pulumi/pulumi-artifactory/pull/930 - these were likely created in the same workflow and the PR should have closed the issue (but maybe the existence of older issues confused thigs?)

- Additionally, the duplicative pull requests did not auto-close when https://github.com/pulumi/pulumi-artifactory/pull/930 merged.

**Comment by guineveresaenger** [comment]
https://github.com/pulumi/pulumi-alicloud/pull/829 on the other hand, closes all 3 identically-named issues.

The main fix here seems to be to not open duplicative issues or pull requests.

**Comment by danielrbradley** [comment]
This was an issue in upgrade-provider which was fixed with https://github.com/pulumi/upgrade-provider/pull/287
