### ISSUE TITLE
Generate Coverage Data job cannot find upstream go.mod

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#1160]
Example failures:

Since Makefile changes in PRs [such as this one](https://github.com/pulumi/pulumi-gcp/pull/2681), we're seeing the `generate coverage data` job not having the `./upstream` submodule available.

https://github.com/pulumi/pulumi-okta/actions/runs/12024901877/job/33569497516
https://github.com/pulumi/pulumi-gcp/actions/runs/12025368466/job/33568908896

**Comment by blampe** [comment]
@guineveresaenger maybe try updating workflows again, Daniel just tweaked this in https://github.com/pulumi/ci-mgmt/pull/1157

**Comment by danielrbradley** [comment]
Yes, it looks like this was solved by #1157 and was rolled out last night
