### ISSUE TITLE
Only Tag providers at the end of the workflow

### ISSUE THREAD

**Issue by stack72** [pulumi/ci-mgmt#137]
Without doing this, there is a chance that a user can download the Go SDK when it's not actually ready to be used

//cc @jkodroff @guineveresaenger

**Comment by jkodroff** [comment]
@stack72 Is this part of what releasebot does, or part of one of the GH workflows?

If it's the former, this issue should go in pulumi/release-bot. If it's the latter, can we assume we mean `release.yml`?

**Comment by stack72** [comment]
That sounds exactly the ticket @guineveresaenger

**Comment by guineveresaenger** [comment]
This issue is now fixed for Terraform providers. Native providers will have to [add an SDK push tag step](https://github.com/pulumi/ci-mgmt/blob/master/provider-ci/providers/ec/repo/.github/workflows/release.yml#L397) to their release workflow Action.
