### ISSUE TITLE
Automerge job times out before all checks are green

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#144]
## Issue details

The automerge feature is timing out before the other checks are green.
Code is here: https://github.com/pulumi/ci-mgmt/blob/master/provider-ci/src/shared-workflows.ts#L27

example PR that should have automerged https://github.com/pulumi/pulumi-aiven/pull/183

### Steps to reproduce

This occurs most often on automated provider action updates, and the time it takes for the other checks to run and succeed is variable, depending on action runner availability.

Expected: Most smaller providers should automerge
Actual: The automerge action times out before the entire check suite is green

**Comment by jkisk** [comment]
Have we considered using the built in automerge functionality instead?  It would need to be allowed in all the relevant repos, then we could turn it on when creating the PRs, and would automerge whenever a green state was achieved.  I set this up for our staging prs in the service, see release.yml there for an example.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by guineveresaenger** [comment]
I love this! We should absolutely do it.
