### ISSUE TITLE
(experiment) consider removing Makefiles

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/ci-mgmt#16]
One of the more frustrating elements of the build process is dealing with the `Makefile` syntax we're currently using:

- It's difficult to generate Makefiles programmatically
- The syntax doesn't lend itself well to multi stage builds
- It's quickly becoming complex

Ideally, we could try and replace this with a task runner which will allow us to generate these files programmatically with jk.

I've had some success before with https://github.com/go-task/task which uses a YAML config file, so we should try it out

**Comment by jkodroff** [comment]
Also:

* We don't use proper file targets in Make, which results in unnecessary work being done.
* Updating 60+ providers manually is a lot of toil.

**Comment by danielrbradley** [comment]
Fixed in #195 based on exploration work in https://github.com/pulumi/pulumi-awsx/pull/859
