### ISSUE TITLE
Artifactory Workflows out of phase with provider

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#186]
Due to our lint step needing go version 1.18, linting will not work in Artifactory.

Because we do add linting steps to all providers, this means that currently, any autogenerated workflow updates against Artifactory from this repo will fail.

Since we bulk generate Workflow files in this repo, we also cannot simply ~walk into Mordor~ overwrite Artifactory's action files, they'd just get overwritten the next time we update this repo.

Solutions welcome - but tracking this here to prevent future confusion.

**Comment by danielrbradley** [comment]
This should be resolved by #195
