### ISSUE TITLE
Java SDK generation & publishing

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/ci-mgmt#203]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- [x] Add makefile targets for `build_java` and `install_java_sdk`
- [x] Add java to CI matrix
- [x] Add Maven and gradle publishing to CI

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/ci-mgmt/pull/213
