### ISSUE TITLE
Community bot not adding messages when contributors attempt to modify generated files

### ISSUE THREAD

**Issue by jkisk** [pulumi/ci-mgmt#245]
see: https://github.com/pulumi/pulumi-aws/pull/2133 and https://github.com/pulumi/pulumi-aws/pull/2091

**Comment by guineveresaenger** [comment]
I ran a test PR and confirmed the bot itself is still working.

Going to dive into pulumi-aws right now to see what's going on.

**Comment by guineveresaenger** [comment]
do we have a pagination issue? https://github.com/pulumi/pulumi-aws/actions/runs/3039168902/jobs/4893787365#step:4:11

**Comment by guineveresaenger** [comment]
It looks like we are missing a `*` in the [filter](https://github.com/pulumi/pulumi-aws/blob/master/.github/workflows/community-moderation.yml#L20) and it is only looking for changes in the top level directory.
