### ISSUE TITLE
Fix GCP service account

### ISSUE THREAD

**Issue by lblackstone** [pulumi/ci-mgmt#251]
### What happened?

I disabled the `travis-ci@pulumi-ci-gcp-provider.iam.gserviceaccount.com` as part of cleanup, but it was apparently still in use for GCP provider CI.

### Steps to reproduce

Example failing test: https://github.com/pulumi/pulumi-google-native/actions/runs/3054711811/jobs/4927543479#step:24:158

### Expected Behavior

CI working

### Actual Behavior

CI not working

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
I'll fix this warning while I'm at it:
```
Warning: "service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
```

**Comment by lblackstone** [comment]
Related: 

- https://github.com/pulumi/org-management/pull/40

**Comment by lblackstone** [comment]
This is causing a bunch of CI jobs to fail, so marking as P0

**Comment by squaremo** [comment]
(Side note: this PR https://github.com/pulumi/pulumi-kubernetes-operator/pull/319 removed the use of GCP clusters for testing pulumi-kubernetes-operator; test runs have succeeded over the last couple of days, so :+1: on that front)
