### ISSUE TITLE
Re-enable automerge of ci-mgmt workflows if safe to do so

### ISSUE THREAD

**Issue by viveklak** [pulumi/ci-mgmt#272]
### What happened?

We had to pause auto-merge of ci-mgmt PRs in https://github.com/pulumi/ci-mgmt/pull/265 and https://github.com/pulumi/ci-mgmt/pull/267 because these were being merged despite build failures. However, we need ci-mgmt to be synced to the relevant providers automatically to avoid issues due to workflows being stale (e.g. pulumi-azure has not yet synced to remove java publish as a blocking step: https://github.com/pulumi/pulumi-azure/blob/master/.github/workflows/release.yml#L351

We need to investigate and ensure automerge can be re-enabled safely at the earliest for the above drift to no longer occur.

### Steps to reproduce

See above.

### Expected Behavior

Automerge occurs only when all of CI passes.

### Actual Behavior

Automerge is currently paused because it was steamrolling despite CI failures.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
This should be addressed as part of https://github.com/pulumi/ci-mgmt/pull/281

**Comment by viveklak** [comment]
#300 includes a summary of the investigations into why this was happening and a plausible solution.

**Comment by t0yv0** [comment]
Closing in favor of https://github.com/pulumi/ci-mgmt/issues/311
