### ISSUE TITLE
GoReleaser Version Update

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#320]
A [recent publish step](https://github.com/pulumi/pulumi-docker/actions/runs/4029329012/jobs/6927428465#step:9:47) failed with "Cannot find GoReleaser latest release".

Upon digging in, it turns out we're using goreleaser-action@v2, while the [latest version of that action](https://github.com/goreleaser/goreleaser-action/releases/tag/v4.2.0) is @v4.

Trialing this out in a manual PR on the affected provider here: https://github.com/pulumi/pulumi-docker/pull/474

**Comment by guineveresaenger** [comment]
We should at least be able to [get a better error message](https://github.com/goreleaser/goreleaser-action/blob/master/src/github.ts#L35)

**Comment by danielrbradley** [comment]
This is no longer relevant as we've removed goreleaser from our tool chain.
