### ISSUE TITLE
Lint Failure during Upgrade: go version mismatch

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#372]
### What happened?

See https://github.com/pulumi/pulumi-newrelic/actions/runs/4467875808/jobs/7847891395?pr=396

### Expected Behavior

Lints pass

### Steps to reproduce

Run a standard upgrade

### Output of `pulumi about`

NA.

### Additional context

We should pin the go version used, then roll out updates from CI mgtm.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
This looks like an opportunity to replace the golangci-lint container with a better job, which has caused us trouble once this quarter already (#324, #330).
