### ISSUE TITLE
build_java sporadically fails for lack of retry on downloading artifacts

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#377]
### What happened?

https://github.com/pulumi/pulumi-snowflake/actions/runs/4471392177/jobs/7856390158#step:18:46

Snowflake PR failed but works upon restart. We need to retry downloading artifacts, or the entire java step. This is rare but happens in practice at scale when we stand up 60+ PRs. 

### Expected Behavior

N/A

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Have we seen this again recently?

**Comment by t0yv0** [comment]
I don't think so. We'd have evidence in more issues linked here if we did.
