### ISSUE TITLE
update-workflows-ecosystem-providers.yml  should tidy up stale PRs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#398]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When update-workflows-ecosystem-providers.yml creates new PRs it should automatically close stale PRs of the same kind that  it makes.

**Comment by jazzyfresh** [comment]
This would be a great improvement, the bot PR set size grows quite rapidly
