### ISSUE TITLE
Ensure all ecosystem provider repos require review on PRs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#417]
### What happened?

Enable branch protections to enforce PR reviews. This is a follow up from a postmortem.

### Expected Behavior

N/A

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
I believe this is enforced by the program in infra/providers/index.ts
