### ISSUE TITLE
Fix node tests across all providers

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#423]
### What happened?

A recent change https://github.com/pulumi/pulumi/pull/12759 makes Pulumi consult package.json when running Node acceptance tests for the providers, which now breaks because they reference non-existing TypeScript output files.  Pulumi CLI uses ts-node to compile the projects in-memory and does not generate these files:

```
"main": "bin/index.js"
"typings": "bin/index.d.ts"
```

Current hypothesis is that before the change these files were simply ignored in acceptance tests. We will verify this shortly before proceeding. 

The suggested remediation is to drop "main" and "typings" from package.json under examples/ from every provider.

If it is true that package.json were not consulted by ProgramTest perhaps another workaround is to remove them from repos so we continue with prior behavior where they "didn't exist in practice."

- [ ] Link to a writeup on the core issue
- [ ] Automate remediation as a source migration in ci-mgmt
- [ ] Roll out to ecosystem providers via update-workflows-ecosystem-providers
- [ ] List out providers that are not covered by the automatic workflow and ensure they are manually updated

### Expected Behavior

Acceptance tests work.

### Steps to reproduce

TBD

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Platform is reverting the change but we should go ahead and fix this up as this removes warnings from the acceptance test process.

**Comment by mjeffryes** [comment]
Do we still need to do this?

**Comment by t0yv0** [comment]
Nope. Node tests are working so we're good to close.
