### ISSUE TITLE
Consider quoting all provider names

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#594]
We encountered an issue with `pulumi-null`'s provider name being evaluated to the null value in Actions.

https://github.com/pulumi/ci-mgmt/pull/592 is attempting to fix that; however we should probably quote all provider names in our Actions as per [code review suggestion](https://github.com/pulumi/ci-mgmt/pull/592#discussion_r1330337342).

**Comment by danielrbradley** [comment]
Fixed as part of https://github.com/pulumi/ci-mgmt/pull/943
