### ISSUE TITLE
Gradual rollout for pulumi and pulumi/pkg updates

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#600]
Coming as a postmortem follow-up from [Package Authoring Broken](https://docs.google.com/document/d/1OE3kHeRiFI6fg1jbLZJNA5ZRUfE9S-xJR9-E9dPTTA4/edit?usp=sharing) there is a need to detect changes in `pulumi gen-sdk` or `pulumi/pkg codegen` that accidentally break community provider builds early so we have a chance to notice and mitigate or else communicate what's about to break.  Most community providers are bridged providers so the mitigation is scoped to bridged providers. Specifically we want to do this:

- stop upgrading pinned pulumi or pulumi/pkg version in providers ahead of the version required by the bridge (change to upgrade-provider)
- double-check the bridge regularly updates to latest pulumi/pkg
- pick a sample provider (pulumi-aiven?) to receive updates
  - ensure it runs bridge updates nightly to pre-release the bridge
  - this also pulls in pulumi/pkg updates as specified in the bridge
  - ensure builds and release are green on this provider
  - if they are broken, fix the bridge immediately 
- space out bridge releases to 1 per week
- communicate breaking changes in bridge release notes 
- when releasing the bridge make sure this provider is working as expected

This makes sure bridge releases publish bridge changes and pulumi/pkg changes that have been end to end tested through builds and releases, therefore establishing a quality gate for both bridge and pulumi changes before they hit the provider fleet or community providers.

**Comment by t0yv0** [comment]
@Frassle @pulumi/providers @mnlumi @ringods follow up from the postmortem. Here's one way we could make this work better. Please let me know if there's concerns before we implement.

**Comment by Frassle** [comment]
Yeh this sounds helpful

**Comment by t0yv0** [comment]
Good point. We can pick a more widely used provider since merging but not releasing does not immediately expose end-users to risk, though it might end up in a situation where next version of the provider goes out with pre-release bridge or needs to wait on release bridge. Which provider would you suggest @iwahbe we could use here to get a better coverage? Cloudflare?

**Comment by iwahbe** [comment]
Cloudflare has 1 test (copied into 4 languages), so it's not much better. Unless we want to use `aws`, `azure` or `gcp`, I think we will just need to pick a medium size provider and add lots of tests.

I would probably go with a small general cloud provider like digital ocean, purely because the provider expects to provide its own ecosystem and can be easily tested without bringing in other configuration.

**Comment by t0yv0** [comment]
Tier 1 are not great options AFAIK. I'll throw a note in ideation. We could also use an ACME provider specifically designed for testing the bridge and not actual use.

**Comment by t0yv0** [comment]
We're doing now a slight variation of the suggested procedure instead https://github.com/pulumi/platform-providers-team/blob/main/playbooks/Release%3A%20Terraform%20Bridge.md as part of weekly releases.

- [x] stop upgrading pinned pulumi or pulumi/pkg version in providers ahead of the version required by the bridge (change to upgrade-provider)
- [x] double-check the bridge regularly updates to latest pulumi/pkg
- [ ] pick a sample provider (pulumi-aiven?) to receive updates
- [ ] ensure it runs bridge updates nightly to pre-release the bridge
- [ ] this also pulls in pulumi/pkg updates as specified in the bridge
- [ ] ensure builds and release are green on this provider
- [ ] if they are broken, fix the bridge immediately
- [x] space out bridge releases to 1 per week
- [x] communicate breaking changes in bridge release notes
- [ ] when releasing the bridge make sure this provider is working as expected

Instead of having a special provider to test, we essentially build all providers against the bridge RC and run their tests and investigate test failures. This procedure has already been shown to be effective in weeding out bugs in pulumi/pkg or the bridge itself before they hit production, such as https://github.com/pulumi/pulumi-terraform-bridge/commit/a0d01d3f8bcd0872c68b89a6ba73871b0cb6ddce or some of the Python [_configure](https://docs.google.com/document/d/1-8h9q1UBPP-xRRjNsnHyxcoDTTxVI9KdtAzEc9xRcvM/edit?usp=sharing) rollout related bugs.

I'm thinking we should close this for the moment. More could be done here along these lines by testing release pipeline through making an actual Python/Node/etc release, as well as having a channel where new bridge versions go to production on some of the providers early.  There's no immediate plans to do this, as we wait to see where we settle with this updated verification procedure.

Please reopen if you still have concerns and we should put some more work in here. Appreciate it.
