### ISSUE TITLE
Use gotestfmt to display bridged provider test results

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#674]
Enhancement request from @danielrbradley  to spruce up test display for bridged providers like we do for natives.

Bonus points if Makefile could detect presence of gotestfmt and thread through it locally.

**Comment by danielrbradley** [comment]
We could install gotestfmt via the makefile so we also get better display on local runs too

**Comment by blampe** [comment]
https://github.com/pulumi/ci-mgmt/pull/1069
