### ISSUE TITLE
Simplify branch protections: sentinel only

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#693]
Per https://github.com/pulumi/ci-mgmt/pull/687#issuecomment-1766798595

would like to simplify branch protections to only require "sentinel" to pass.

Using branch protections that mention individual step names is making the system sensitive to refactors of the CI job layout. 

It appears that relying on the sentinel is now safe.

**Comment by danielrbradley** [comment]
Fixed in #948
