### ISSUE TITLE
Remove noisy Slack alerting for test upgrade-provider jobs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#699]
AS part of the pulumi-terraform-bridge release validation

Maintainers now run https://github.com/pulumi/pulumi-terraform-bridge/blob/master/.github/workflows/update-providers-test.yml

This generates a LOT of PRs that try to upgrade providers to a pre-release bridge version.

These PRs make noise in [#provider-upgrade-publish-status](https://pulumi.slack.com/archives/C052BQ410UA) 

The ideal outcome here is that these helper PRs do not alert into #provider-upgrade-publish-status . 

They are kind of expected to fail sometimes as they're part of testing, not production; similarly success notification is not meaningful as the PRs may send a success notification but actually fail tests.

**Comment by danielrbradley** [comment]
Fixes in #1012
