### ISSUE TITLE
Remove custom action from Docker image builds?

### ISSUE THREAD

**Issue by jkodroff** [pulumi/ci-mgmt#71]
The [custom GH Action](https://github.com/pulumi/action-docker-build) we use to build [our Docker images](https://github.com/pulumi/pulumi/tree/master/docker) was created at a time when the official Docker GH actions were not adequate for our needs.

Investigate whether we can move away from maintaining a custom GH Action in favor of one of the following, in order of preference:

1. Official Docker actions
2. Straight `run` (shell) commands.

**Comment by stack72** [comment]
This was in the wrong repo and has been solved
