### ISSUE TITLE
Stateless Provider Upgrade Tracking and Automation

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#724]
We currently run a zapier job connection to an AWS Lambda to kickstart our automation on bridged provider upgrades.

If this job fails, nothing else happens, and we receive no notifications on new providers to update. This happened, and it took us a week to catch. To get us back on track vis a vis provider upgrades and to mitigate this issue permanently, we should transition to a less brittle path.

### New Plan
TODO

### Implementation
TODO

**Comment by guineveresaenger** [comment]
Current implementation: 

https://github.com/pulumi/github-issue-automation

Instructions to add a new provider: https://github.com/pulumi/platform-providers-team/blob/main/playbooks/Onboard%20provider%3A%20internal.md

****************
The gist of the new plan I'd suggest is as follows:

- Remove the Zapier/AWS Lambda roundtrip in favor of a GitHub Action that runs on a cron schedule, asking the GitHub API for a latest release for any given provider. Basically, this changes the model from a push-based approach (which has several points of failure) to a poll-based approach (which, even if it fails, can be idempotently rerun and "recover" missed history).

- https://github.com/pulumi/github-issue-automation/blob/main/lambda/new-release-handler/main.go includes some logic around what we consider a valid release, which should be preserved. Additionally, we should not need to keep a map of terraform providers - this information is available, in-repo, as part of each provider's CI config.

- Using "the existence of an issue that has `upgrade terraform-provider-foo` in its title" as a trigger for upgrades should be removed, although this may be a later refinement.

A few details:

- The cron GHA will create an upgrade issue, and ideally it should immediately trigger an upgrade build, linking this build to the issue created.

- It seems as though the best approach here is to alter https://github.com/pulumi/upgrade-provider to have an option to query the upstream latest release, and use that inside the cron Action. Later, we can refactor and remove the need to rely on detecting open upgrade issues on the Pulumi provider.

**Comment by guineveresaenger** [comment]
> To get idempotency, I think we will need to have detecting open issues depend on the repo in some way, since we need to understand the current version to know if we need to upgrade.

I find this whole process of polling existing issues to be disturbingly brittle, but realized with chagrin that with the git submodule approach, we can't just read the upstream version from go.mod. 🤔 
Maybe write the upstream version to `.ci-mgmt.yaml`? Anyway, this is not immediately necessary, just something to ponder.

**Comment by iwahbe** [comment]
> > To get idempotency, I think we will need to have detecting open issues depend on the repo in some way, since we need to understand the current version to know if we need to upgrade.
> 
> I find this whole process of polling existing issues to be disturbingly brittle, but realized with chagrin that with the git submodule approach, we can't just read the upstream version from go.mod. 🤔 Maybe write the upstream version to `.ci-mgmt.yaml`? Anyway, this is not immediately necessary, just something to ponder.

For good or for ill, we actually can, and do. The git submodule records the SHA of the upstream, and we query the upstream GH repo to resolve that SHA back into a version.

We need to do this for patched providers (git submodule), and we need to do this for plain providers (no submodule) when the upstream doesn't tag their release correctly for go.

**Comment by blampe** [comment]
This looks great! Anything that can be re-run to clean up any missed work would be an improvement.

I’m not sure what sort of SLA we have around these upgrades, but we can dial that in by running the cron more regularly. (As long as things happen within a day that seems reasonable IMO.)

Would it be possible to post a Slack notification if/when something goes wrong? One of the problems with the existing workflow is we didn't know it was broken for a week 🤯

**Comment by guineveresaenger** [comment]
First phase of the plan via pulumi/upgrade-provider#207.
Next stop: Add a Workflow on a cron that triggers this and set it on a few providers.

> Would it be possible to post a Slack notification if/when something goes wrong? One of the problems with the existing workflow is we didn't know it was broken for a week 🤯

Yes, this is something we do elsewhere and we'll add it to the check-upgrade job.

**Comment by guineveresaenger** [comment]
update 12/5:

I [tested out the new upgrade-provider option](https://github.com/pulumi/upgrade-provider/pull/207/commits/76b9fab627d8c180d280ac234feebce80f8dc076) on [pulumi-akamai](https://github.com/pulumi/pulumi-akamai/blob/ce6006af8a6f34cbeb14810481ba57d2c0735c5a/.github/workflows/check-upstream-upgrade.yml).
The results look promising:

The check-upstream-upgrade Action:

- runs on dispatch (for testing; will add a cron tab)
- [creates an upgrade issue if none exists that is open](https://github.com/pulumi/pulumi-akamai/pull/353); the prior blocked issue [was closed for the duration of this run](https://github.com/pulumi/pulumi-akamai/issues/313#issuecomment-1841248250) to verify
- it does [not create a new upgrade issue if one already exists](https://github.com/pulumi/pulumi-akamai/actions/runs/7104045787/job/19338136772), which is reported as a success (as it should)
- it [creates a P1 workflow failure when the job itself fails](https://github.com/pulumi/pulumi-akamai/issues/354) as per our global triage process

- The Workflow itself [does not yet reliably report a failure to Slack](https://github.com/pulumi/pulumi-akamai/actions/runs/7104384563/job/19339206826) because GHA are The Worst, basically.

**Comment by guineveresaenger** [comment]
follow-up: [Failure report to Slack](https://pulumi.slack.com/archives/C052BQ410UA/p1701799399122449) achieved in this job: https://github.com/pulumi/pulumi-akamai/actions/runs/7104707347/job/19340307540

**Comment by guineveresaenger** [comment]
Update: Trial PR was merged; ten providers were removed from the Zap.

Will be watching for updates to [update issues on these repos](https://github.com/issues?q=is%3Aissue+author%3Apulumi-bot+archived%3Afalse+label%3Akind%2Fenhancement+repo%3Apulumi%2Fpulumi-linode+repo%3Apulumi%2Fpulumi-digitalocean+repo%3Apulumi%2Fpulumi-vsphere+repo%3Apulumi%2Fpulumi-gitlab+repo%3Apulumi%2Fpulumi-datadog+repo%3Apulumi%2Fpulumi-consul+repo%3Apulumi%2Fpulumi-signalfx+repo%3Apulumi%2Fpulumi-fastly+repo%3Apulumi%2Fpulumi-alicloud+repo%3Apulumi%2Fpulumi-rancher2+) continuing.

**Comment by guineveresaenger** [comment]
We [have a winner](https://github.com/pulumi/pulumi-vsphere/issues/381)!

We also have two stragglers due to a bug in detecting the upstream org/repo name: https://github.com/pulumi/upgrade-provider/issues/213

We need to fix that bug first before continuing rollout.

**Comment by guineveresaenger** [comment]
Update: Rolled out to all providers not Tier 1.

While deleting the Zaps, I discovered we also detect upgrades to https://github.com/hashicorp/terraform using Zaps. These map to pulumi-terraform. I left that Zap running for now, alongside gcp, azure, and aws.

**Comment by guineveresaenger** [comment]
Update: All upgradeable providers are now migrated to this way of checking for upgrades.

OUtstanding:

- deprecate github-issue-automation
- update the playbook entry to remove Zapier integrations

**Comment by guineveresaenger** [comment]
Closing this via deprecation of github-issue-automation and pulumi/platform-providers-team#135. 🎉
