### ISSUE TITLE
Continuously release providers without upstream updates

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#726]
The bridge constantly receives updates and bug fixes. These are blasted out to our providers and incorporated into their default branch.

Bridged providers are released in cadence with their upstream. Some upstream providers are stable, and so release rarely. This means that bridge fixes don't get to our users. 

We should make sure that the latest provider release is no more than 8 bridge releases out of date. For a provider that doesn't release on its own, that would mean an extra release every 2 months. These will be patch releases.

---

This process should be part of our automation pipeline, possible attached to bridge updates. The design still needs to be written and then specced out.

**Comment by guineveresaenger** [comment]
There are two approaches that use existing tooling and avoid re-calculating tag comparisons.

1. Use `upgrade-provider`

During a `--kind=bridge` upgrade, query the `latest` release endpoint, extract the date, run a time comparison, and apply a `release/patch` label via `upgrade-provider` on the PR that updates the bridge, if the release is older than 8 weeks.
Advantage: can test this behavior; keeps upgrade logic contained to single tool
Disadvantage: Adding more logic to upgrade-provider; need to reconcile with inherent assumptions about patch releases; a little trickier to implement

2. Use GHA

Run a cron job every 2 or 4 weeks that runs a script that checks `latest`, runs a time comparison, and if `latest` is older than 8 weeks, call the release-bot endpoint with `version=patch`.
Advantage: Avoids a lot of the complexity inherent to `upgrade-provider`
Disadvantage: Creates a new script to maintain centrally; less connected to existing system

I was slightly leaning towards (1) but writing it out I may prefer (2) to avoid tooling sprawl.

**Comment by guineveresaenger** [comment]
> We already release patch providers with arbitrary bridge updates. I don't see how the proposed change will exacerbate that.

I just want to make sure we don't override patch upgrades that come from different sources.

do you mean we sometimes run a bridge update and tell upgrade-provider "please make this a patch release"? when/how does this happen?

**Comment by iwahbe** [comment]
> I just want to make sure we don't override patch upgrades that come from different sources.

I think I failed to understand your original concern.

> do you mean we sometimes run a bridge update and tell upgrade-provider "please make this a patch release"? when/how does this happen?

No. I thought you were concerned that we would make a bridge release that should be a minor version, but is released as a patch. I was saying we already do that, if the next upstream upgrade is itself a patch.
