### ISSUE TITLE
Every release is assumed to be the latest

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#728]
This came up when trying to release v5 AWS patch when keeping v6 as latest.

https://github.com/pulumi/pulumi-aws/actions/runs/6945236404

The release succeeded but it sent a PR to registry to update the latest docs for AWS with 5.43.0 which is not what we wanted. 

It also set 5.43.0 as the latest release in the GitHub releases in pulumi-aws.

**Comment by danielrbradley** [comment]
This was fixed by:
- https://github.com/pulumi/ci-mgmt/issues/1012
