### ISSUE TITLE
Don't create upgrade issues for beta releases

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#749]
Our new automation created the issue: https://github.com/pulumi/pulumi-postgresql/issues/336.

We shouldn't see upgrade issues for beta releases.

**Comment by guineveresaenger** [comment]
This is an issue in https://github.com/pulumi/upgrade-provider - tooling assumes that `latest` is a stable version. My suggestion would be to add a catch for non-major-minor-patch and skip creating the issue.
