### ISSUE TITLE
Change the name of example providers

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#756]
This repo has config for the AWS provider, but it is not the real config since that lives in pulumi-aws. To avoid confusion, we should change the name of these example providers to something clearly phony, like `example1`, `example2`, ...

See https://github.com/pulumi/ci-mgmt/pull/755 for details

**Comment by t0yv0** [comment]
I think the added warning comments are fine so no need to work this out.

**Comment by iwahbe** [comment]
Sounds good. Fixed in https://github.com/pulumi/ci-mgmt/pull/755/commits/4de683b996dddf184e25ede1072ea8282dae77e1.
