### ISSUE TITLE
Sequential test group for tests which depend on environment

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/ci-mgmt#805]
We recently had a flaky test in gcp which I strongly believe was caused by interactions with other tests' environments/ the gcloud cli.

We could fix this by having a separate test group which runs the tests one at a time.

https://github.com/pulumi/pulumi-gcp/issues/1610

## Native Providers

- [ ] aws-apigateway
- [ ] aws-native
- [ ] awsx
- [ ] azure-native
- [ ] command
- [ ] eks
- [ ] google-native
- [ ] kubernetes

### Tier 1

- [ ] aws
- [ ] gcp
- [ ] azure
- [ ] azuread

### Tier 2

- [ ] aiven
- [ ] akamai
- [ ] alicloud
- [ ] archive
- [ ] artifactory
- [ ] auth0
- [ ] azuredevops
- [ ] civo
- [ ] cloudamqp
- [ ] cloudflare
- [ ] cloudinit
- [ ] confluentcloud
- [ ] consul
- [ ] databricks
- [ ] datadog
- [ ] digitalocean
- [ ] dnsimple
- [ ] docker
- [ ] ec
- [ ] external
- [ ] f5bigip
- [ ] fastly
- [ ] github
- [ ] gitlab
- [ ] hcloud
- [ ] http
- [ ] kafka
- [ ] keycloak
- [ ] kong
- [ ] libvirt
- [ ] linode
- [ ] local
- [ ] mailgun
- [ ] minio
- [ ] mongodbatlas
- [ ] mysql
- [ ] newrelic
- [ ] nomad
- [ ] ns1
- [ ] null
- [ ] oci
- [ ] okta
- [ ] onelogin
- [ ] openstack
- [ ] opsgenie
- [ ] pagerduty
- [ ] postgresql
- [ ] rabbitmq
- [ ] rancher2
- [ ] random
- [ ] rke
- [ ] signalfx
- [ ] slack
- [ ] snowflake
- [ ] splunk
- [ ] spotinst
- [ ] sumologic
- [ ] tailscale
- [ ] tls
- [ ] vault
- [ ] venafi
- [ ] vsphere
- [ ] wavefront

**Comment by t0yv0** [comment]
This would be highly unwelcome as this balloons CI expenses. Our tests are very IO-bound and it's not a good use of GHA time to test them sequentially. The test in question is leaky but can be fixed by isolating it properly from the environment variable modifications I believe.

**Comment by t0yv0** [comment]
It's not about frequency, it's' about doing the right thing IMO, we should fix test isolation without compromising parallelism.
