### ISSUE TITLE
Native provider fails to publish

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/ci-mgmt#847]
When merging:
- https://github.com/pulumi/pulumi-aws-native/pull/1413

The `master` workflow fails with [various errors](https://github.com/pulumi/pulumi-aws-native/actions/runs/8280097860/job/22656434168):
```
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
sudo: docker: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
sudo: swapoff: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 173: free: command not found
```

Reverted in:
- https://github.com/pulumi/pulumi-aws-native/pull/1421

This might have been caused by one of:
- https://github.com/pulumi/ci-mgmt/pull/846
- https://github.com/pulumi/ci-mgmt/pull/845

cc: @mjeffryes @rquitales

**Comment by rquitales** [comment]
It seems like the disk cleaning action is too aggressive in freeing up space. We'll need to take another look into fine-tuning the action @mjeffryes
