### ISSUE TITLE
Roll out PULUMI_CONVERT=1 to tier 2 providers

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#889]
### Tier 1

- [x] aws
- [x] gcp
- [x] azure
- [x] azuread

### Tier 2

- [X] aiven https://github.com/pulumi/pulumi-aiven/pull/582
- [X] akamai https://github.com/pulumi/pulumi-akamai/pull/490
- [x] alicloud https://github.com/pulumi/pulumi-alicloud/pull/650
- [x] archive https://github.com/pulumi/pulumi-archive/pull/182
- [x] artifactory https://github.com/pulumi/pulumi-artifactory/pull/698
- [x] auth0 https://github.com/pulumi/pulumi-auth0/pull/500
- [x] azuredevops https://github.com/pulumi/pulumi-azuredevops/pull/362
- [x] civo https://github.com/pulumi/pulumi-civo/pull/463
- [x] cloudamqp https://github.com/pulumi/pulumi-cloudamqp/pull/419
- [x] cloudflare https://github.com/pulumi/pulumi-cloudflare/pull/735
- [x] cloudinit https://github.com/pulumi/pulumi-cloudinit/pull/290
- [x] confluentcloud https://github.com/pulumi/pulumi-confluentcloud/pull/434
- [x] consul https://github.com/pulumi/pulumi-consul/pull/407
- [x] databricks https://github.com/pulumi/pulumi-databricks/pull/423
- [x] datadog https://github.com/pulumi/pulumi-datadog/pull/514
- [ ] digitalocean
- [X] dnsimple https://github.com/pulumi/pulumi-dnsimple/pull/377
- [x] docker https://github.com/pulumi/pulumi-docker/pull/1064
- [x] ec https://github.com/pulumi/pulumi-ec/pull/318
- [x] external https://github.com/pulumi/pulumi-external/pull/175
- [x] f5bigip https://github.com/pulumi/pulumi-f5bigip/pull/446
- [x] fastly https://github.com/pulumi/pulumi-fastly/pull/505
- [x] github https://github.com/pulumi/pulumi-github/pull/640
- [x] gitlab https://github.com/pulumi/pulumi-gitlab/pull/567
- [x] hcloud https://github.com/pulumi/pulumi-hcloud/pull/473
- [x] http https://github.com/pulumi/pulumi-http/pull/160
- [x] kafka https://github.com/pulumi/pulumi-kafka/pull/391
- [x] keycloak https://github.com/pulumi/pulumi-keycloak/pull/465
- [x] kong https://github.com/pulumi/pulumi-kong/pull/374
- [x] libvirt https://github.com/pulumi/pulumi-libvirt/pull/311
- [x] linode https://github.com/pulumi/pulumi-linode/pull/570
- [x] local https://github.com/pulumi/pulumi-local/pull/180
- [x] mailgun https://github.com/pulumi/pulumi-mailgun/pull/354
- [x] minio https://github.com/pulumi/pulumi-minio/pull/360
- [x] mongodbatlas https://github.com/pulumi/pulumi-mongodbatlas/pull/446
- [x] mysql https://github.com/pulumi/pulumi-mysql/pull/453
- [x] newrelic https://github.com/pulumi/pulumi-newrelic/pull/705
- [x] nomad https://github.com/pulumi/pulumi-nomad/pull/301
- [x] ns1 https://github.com/pulumi/pulumi-ns1/pull/419
- [x] null https://github.com/pulumi/pulumi-null/pull/161
- [x] oci https://github.com/pulumi/pulumi-oci/pull/434
- [x] okta https://github.com/pulumi/pulumi-okta/pull/591
- [x] onelogin https://github.com/pulumi/pulumi-onelogin/pull/287
- [x] openstack https://github.com/pulumi/pulumi-openstack/pull/565
- [x] opsgenie https://github.com/pulumi/pulumi-opsgenie/pull/366
- [x] pagerduty https://github.com/pulumi/pulumi-pagerduty/pull/468
- [X] postgresql https://github.com/pulumi/pulumi-postgresql/pull/446
- [x] rabbitmq https://github.com/pulumi/pulumi-rabbitmq/pull/350
- [x] rancher2 https://github.com/pulumi/pulumi-rancher2/pull/445
- [x] random https://github.com/pulumi/pulumi-random/pull/890
- [x] rke https://github.com/pulumi/pulumi-rke/pull/332
- [x] signalfx https://github.com/pulumi/pulumi-signalfx/pull/453
- [x] slack https://github.com/pulumi/pulumi-slack/pull/307
- [x] snowflake https://github.com/pulumi/pulumi-snowflake/pull/569
- [x] splunk https://github.com/pulumi/pulumi-splunk/pull/328
- [x] spotinst https://github.com/pulumi/pulumi-spotinst/pull/658
- [x] sumologic https://github.com/pulumi/pulumi-sumologic/pull/336
- [x] tailscale https://github.com/pulumi/pulumi-tailscale/pull/396
- [x] tls https://github.com/pulumi/pulumi-tls/pull/483
- [x] vault https://github.com/pulumi/pulumi-vault/pull/485
- [x] venafi https://github.com/pulumi/pulumi-venafi/pull/328
- [x] vsphere https://github.com/pulumi/pulumi-vsphere/pull/475
- [x] wavefront https://github.com/pulumi/pulumi-wavefront/pull/390

**Comment by t0yv0** [comment]
@pulumi/providers hi team if you can help me getting these reviewed I'll appreciate it very much. Most are fairly mechanical but if you spot something odd it's worth discussing.

**Comment by VenelinMartinov** [comment]
Spotted a few possible regressions:

Another possible regression: https://github.com/pulumi/pulumi-archive/pull/182

Some here too: https://github.com/pulumi/pulumi-artifactory/pull/698/files
AlpineRepository is dropped because of terraform in the resource name - should we be renaming that?
DistributionPublicKey is dropped and I can't see why.

https://github.com/pulumi/pulumi-civo/pull/463/files
This one also has some

https://github.com/pulumi/pulumi-cloudflare/pull/735/files too

https://github.com/pulumi/pulumi-github/pull/640/files has some new examples but also some dropped ones

https://github.com/pulumi/pulumi-random/pull/890/files in RandomInteger.java has a
`.action(%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference))` - this one seems odd? It's fine in non-Java sdks. Is this a panic which we printed in the example?

https://github.com/pulumi/pulumi-tls/pull/483/files drops a few examples too.

There seems to be a common theme I spotted in the dropped examples related to file operations perhaps? (edited)

**Comment by t0yv0** [comment]
Some examples were dropped from missing std reference.

- archive is addressed
- artifactory is addressed
- civo is addressed

**Comment by t0yv0** [comment]
cloudflare is addressed

**Comment by t0yv0** [comment]
tls is addressed

**Comment by t0yv0** [comment]
Addressed it all. All ready to go! 

Except for:

- Random (blocked on panic rendered into Java example)
- Digital Ocean (blocked on panic in convereter)

**Comment by t0yv0** [comment]
Per @mjeffryes merging the rest of unblocked PRs without waiting for approvals.

**Comment by t0yv0** [comment]
Last one: https://github.com/pulumi/pulumi-digitalocean/pull/710

**Comment by VenelinMartinov** [comment]
Should we default enable this in the tf provider boilerplate too? @t0yv0

**Comment by t0yv0** [comment]
Not needed when it becomes the default bridge behavior it will enable itself.
