### ISSUE TITLE
Embed version in SDKs

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/ci-mgmt#915]
Part of https://github.com/pulumi/home/issues/3372

1. Enable embedding version number in each language's SDK

```go
RespectSchemaVersion: true
```

2. Configure ci-mgmt

Versions are stable within the same major version for local development but will be updated during the build in CI.

```yaml
# These files are updated with the real version number
worktreeAllowedChanges: |-
  sdk/**/pulumi-plugin.json
  sdk/dotnet/Pulumi.*.csproj
  sdk/go/*/internal/pulumiUtilities.go
  sdk/nodejs/package.json
  sdk/python/pyproject.toml

publish:
  goSdk:
    usePush: true
```

## Native Providers

PR for the managed providers: https://github.com/pulumi/ci-mgmt/pull/925

- [x] aws-apigateway (not managed) [PR](https://github.com/pulumi/pulumi-aws-apigateway/pull/161)
- [x] aws-native [CI PR](https://github.com/pulumi/pulumi-aws-native/pull/1538) & [Schema PR](https://github.com/pulumi/pulumi-aws-native/pull/1539)
- [x] awsx (not managed) [PR](https://github.com/pulumi/pulumi-awsx/pull/1297)
- [x] azure-native (not managed) [PR](https://github.com/pulumi/pulumi-azure-native/pull/3289)
- [x] command [CI PR](https://github.com/pulumi/pulumi-command/pull/434) & [Schema PR](https://github.com/pulumi/pulumi-command/pull/438)
- [x] docker-build [CI PR](https://github.com/pulumi/pulumi-docker-build/pull/66) & [Schema PR](https://github.com/pulumi/pulumi-docker-build/pull/68)
- [x] eks (not managed) [PR](https://github.com/pulumi/pulumi-eks/pull/1232)
- [x] google-native (deprecated)
- [x] kubernetes [CI PR](https://github.com/pulumi/pulumi-kubernetes/pull/3008) & [Schema PR](https://github.com/pulumi/pulumi-kubernetes/pull/3028)
- [x] [kubernetes-cert-manager](https://github.com/pulumi/pulumi-kubernetes-cert-manager) [CI PR](https://github.com/pulumi/pulumi-kubernetes-cert-manager/pull/60) & [Schema PR](https://github.com/pulumi/pulumi-kubernetes-cert-manager/pull/67)

## Bridged Providers

PR: https://github.com/pulumi/ci-mgmt/pull/920

Bridged provider mass-update run: https://github.com/pulumi/ci-mgmt/actions/runs/9090224158/job/24992409444

### Tier 1

- [x] aws [PR](https://github.com/pulumi/pulumi-aws/pull/3938)
- [x] gcp [PR](https://github.com/pulumi/pulumi-gcp/pull/1994)
- [x] azure [initial](https://github.com/pulumi/pulumi-azure/pull/2024) & [excluding extra files](https://github.com/pulumi/pulumi-azure/pull/2033)
- [x] azuread [PR](https://github.com/pulumi/pulumi-azuread/pull/1054)

### Tier 2

- [x] aiven [PR](https://github.com/pulumi/pulumi-aiven/pull/610)
- [x] akamai [PR](https://github.com/pulumi/pulumi-akamai/pull/516)
- [x] alicloud [PR](https://github.com/pulumi/pulumi-alicloud/pull/684)
- [x] archive [PR](https://github.com/pulumi/pulumi-archive/pull/205)
- [x] artifactory [PR](https://github.com/pulumi/pulumi-artifactory/pull/737)
- [x] auth0 [PR](https://github.com/pulumi/pulumi-auth0/pull/541)
- [x] azuredevops [PR](https://github.com/pulumi/pulumi-azuredevops/pull/386)
- [x] civo [PR](https://github.com/pulumi/pulumi-civo/pull/498)
- [x] cloudamqp [PR](https://github.com/pulumi/pulumi-cloudamqp/pull/440)
- [x] cloudflare [PR](https://github.com/pulumi/pulumi-cloudflare/pull/775)
- [x] cloudinit [PR](https://github.com/pulumi/pulumi-cloudinit/pull/322)
- [x] confluentcloud [PR](https://github.com/pulumi/pulumi-confluentcloud/pull/468)
- [x] consul [PR](https://github.com/pulumi/pulumi-consul/pull/431)
- [x] databricks [PR](https://github.com/pulumi/pulumi-databricks/pull/467)
- [x] datadog [PR](https://github.com/pulumi/pulumi-datadog/pull/539)
- [x] digitalocean [PR](https://github.com/pulumi/pulumi-digitalocean/pull/717)
- [x] dnsimple [PR](https://github.com/pulumi/pulumi-dnsimple/pull/402)
- [x] docker [PR](https://github.com/pulumi/pulumi-docker/pull/1096)
- [x] ec [PR](https://github.com/pulumi/pulumi-ec/pull/343)
- [x] external [PR](https://github.com/pulumi/pulumi-external/pull/199)
- [x] f5bigip [PR](https://github.com/pulumi/pulumi-f5bigip/pull/472)
- [x] fastly [PR](https://github.com/pulumi/pulumi-fastly/pull/537)
- [x] github [PR](https://github.com/pulumi/pulumi-github/pull/664)
- [x] gitlab [PR](https://github.com/pulumi/pulumi-gitlab/pull/603)
- [x] hcloud [PR](https://github.com/pulumi/pulumi-hcloud/pull/507)
- [x] http [PR](https://github.com/pulumi/pulumi-http/pull/185)
- [x] ise [PR](https://github.com/pulumi/pulumi-ise/pull/18)
- [x] kafka [initial](https://github.com/pulumi/pulumi-kafka/pull/410) & [follow-up](https://github.com/pulumi/pulumi-kafka/pull/422)
- [x] keycloak [PR](https://github.com/pulumi/pulumi-keycloak/pull/492)
- [x] kong [PR](https://github.com/pulumi/pulumi-kong/pull/398)
- [x] libvirt [PR](https://github.com/pulumi/pulumi-libvirt/pull/336)
- [x] linode [PR](https://github.com/pulumi/pulumi-linode/pull/601)
- [x] local [PR](https://github.com/pulumi/pulumi-local/pull/203)
- [x] mailgun [PR](https://github.com/pulumi/pulumi-mailgun/pull/380)
- [x] minio [PR](https://github.com/pulumi/pulumi-minio/pull/387)
- [x] mongodbatlas [PR](https://github.com/pulumi/pulumi-mongodbatlas/pull/470)
- [x] mysql [PR](https://github.com/pulumi/pulumi-mysql/pull/476)
- [x] newrelic [PR](https://github.com/pulumi/pulumi-newrelic/pull/748)
- [x] nomad [PR](https://github.com/pulumi/pulumi-nomad/pull/325)
- [x] ns1 [PR](https://github.com/pulumi/pulumi-ns1/pull/443)
- [x] null [PR](https://github.com/pulumi/pulumi-null/pull/185)
- [x] oci [PR](https://github.com/pulumi/pulumi-oci/pull/467)
- [x] okta [PR](https://github.com/pulumi/pulumi-okta/pull/618)
- [x] onelogin [PR](https://github.com/pulumi/pulumi-onelogin/pull/312)
- [x] openstack [PR](https://github.com/pulumi/pulumi-openstack/pull/589)
- [x] opsgenie [PR](https://github.com/pulumi/pulumi-opsgenie/pull/391)
- [x] pagerduty [PR](https://github.com/pulumi/pulumi-pagerduty/pull/496)
- [x] postgresql [PR](https://github.com/pulumi/pulumi-postgresql/pull/472)
- [x] rabbitmq [PR](https://github.com/pulumi/pulumi-rabbitmq/pull/374)
- [x] rancher2 [PR](https://github.com/pulumi/pulumi-rancher2/pull/469)
- [x] random [first-spike](https://github.com/pulumi/pulumi-random/pull/916), [PR](https://github.com/pulumi/pulumi-random/pull/924)
- [x] rke [PR](https://github.com/pulumi/pulumi-rke/pull/361)
- [x] signalfx [PR](https://github.com/pulumi/pulumi-signalfx/pull/477)
- [x] slack [PR](https://github.com/pulumi/pulumi-slack/pull/332)
- [x] snowflake [PR](https://github.com/pulumi/pulumi-snowflake/pull/605)
- [x] splunk [PR](https://github.com/pulumi/pulumi-splunk/pull/353)
- [x] spotinst [PR](https://github.com/pulumi/pulumi-spotinst/pull/697)
- [x] sumologic [PR](https://github.com/pulumi/pulumi-sumologic/pull/360)
- [x] tailscale [PR](https://github.com/pulumi/pulumi-tailscale/pull/424)
- [x] tls [PR](https://github.com/pulumi/pulumi-tls/pull/513)
- [x] vault [PR](https://github.com/pulumi/pulumi-vault/pull/511)
- [x] venafi [PR](https://github.com/pulumi/pulumi-venafi/pull/349)
- [x] vsphere [PR](https://github.com/pulumi/pulumi-vsphere/pull/499)
- [x] wavefront [PR](https://github.com/pulumi/pulumi-wavefront/pull/414)

**Comment by mikhailshilkov** [comment]
We have a few newly bridged providers, does it need to land there too?

- ise
- scm
- dbtcloud
- sdwan
- meraki
