### ISSUE TITLE
upgrade.sh: Allow for unpatched submodule

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#991]
For providers with upstream dependencies that do not follow Go module versioning conventions, such as p-vault and p-pagerduty, we  would like to be able to pull in the upstream as a submodule, but without actually needing any patches.

https://github.com/pulumi/ci-mgmt/pull/983 attempted to allow empty patches but this failed during `make upstream.rebase` and had to be reverted.

**Comment by iwahbe** [comment]
We are using the reverted behavior in 2 providers.
